{{- if .Values.integrations.eso.add -}}
  {{- if .Values.integrations.imageregistry.add -}}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: azure-container-registry-eso
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.eso.clustersecretstore }} 
    kind: ClusterSecretStore
  target:
    name: {{ .Values.integrations.imageregistry.secretname }}  
    template:
      type: kubernetes.io/dockerconfigjson  
      data:
        .dockerconfigjson: 
          '{
              "auths": {
                  "{{ .registryHost }}": {
                      "username": "{{ .registryName }}",
                      "password": "{{ .password }}",
                      "auth": "{{ printf "%s:%s" .registryName .password | b64enc }}"
                  }
              }
          }'  
  data: 
  - secretKey: registryName
    remoteRef:
      key: secret/{{ .Values.registryusername }} 
  - secretKey: registryHost
    remoteRef:
      key: secret/{{ .Values.registryhostname }} 
  - secretKey: password
    remoteRef:
      key: secret/{{ .Values.registrypassword }} 
  {{- end -}}
{{- end -}}
