{{- if .Values.integrations.eso.add -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.eso.clustersecretstore }}
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      tenantId: {{ .Values.eso.akvtenantid }}
      vaultUrl: https://{{ .Values.eso.vaultname }}.vault.azure.net
      authSecretRef:
        clientId:
          name: {{ .Values.eso.esoreadsecret }}
          key: ClientID
          namespace: {{ .Values.eso.esoreadsecretns }}
        clientSecret:
          name: {{ .Values.eso.esoreadsecret }}
          key: ClientSecret
          namespace: {{ .Values.eso.esoreadsecretns }}
{{- end -}}