{{- if .Values.storageaccount.file.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageaccount.file.sc_name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
parameters:
  resourceGroup: {{ .Values.storageaccount.resourcegroup }}
  server: {{ .Values.storageaccount.name }}.file.core.windows.net"
  skuName: {{ .Values.storageaccount.file.sku }}
  storageAccount: {{ .Values.storageaccount.name }}
  secretName: {{ .Values.storageaccount.file.secretname }}
  secretNamespace: "default"
  shareName: {{ .Values.storageaccount.file.nfs_sharename }}
  networkEndpointType: privateEndpoint
  protocol: nfs
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
{{- end -}}