{{- if .Values.integrations.eso.add -}}
  {{- if .Values.integrations.imageregistry.add -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
  - name: {{ .Values.integrations.imageregistry.secretname }}  
  {{- end -}}
{{- end -}}
