{{- if .Values.integrations.extendedlogging.enabled -}}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.integrations.extendedlogging.lokistack }}
  namespace: openshift-logging 
spec:
  size: {{ .Values.integrations.extendedlogging.lokisize }}
  storage:
    schemas:
    - version: v12
      effectiveDate: "2022-06-01"
    secret:
      name: {{ .Values.integrations.extendedlogging.secret_name }}
      type: azure
      credentialMode: 
  storageClassName: {{ if .Values.storageaccount.file.create }}azurefiles-premium{{ else }}managed-premium{{ end }}
  tenants:
    mode: openshift-logging 
{{- end -}}